COURSE_QDRANT_URL = "https://7d9f7f14-94e0-46f5-b717-a4d42c3005a1.us-east4-0.gcp.cloud.qdrant.io"
COURSE_QDRANT_KEY = "lderCoRfPpKc4FrG0ix50lw9gWgbjrEg8R7MpIe1zaZRT3yFKV67nA"
COURSE_COLLECTION = "my_books"
COUNSELLING_QDRANT_URL = "https://7d9f7f14-94e0-46f5-b717-a4d42c3005a1.us-east4-0.gcp.cloud.qdrant.io"
COUNSELLING_QDRANT_KEY = "lderCoRfPpKc4FrG0ix50lw9gWgbjrEg8R7MpIe1zaZRT3yFKV67nA"
COUNSELLING_COLLECTION = "yt_transcription"
GROQ_API_KEY = "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"
