QDRANT_URL =  "https://debb3dec-2da1-4bb9-af6a-856542d7dcfa.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY =  "Sf1upsc81yIRRPPV1BWFFSHqNzsKo6u653uyn4ziWiE1rmgm6dkoGA"
GROQ_API_KEY = "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"
COLLECTION_NAME = "BSWlinks"
